### GET all shops
GET http://localhost:8080/webapi/shops

### get all shops with params
GET http://localhost:8080/webapi/shops?phrase=foo
custom-header: custom-value
Cookie: some-cookie=some-value

### get shop by id
GET http://localhost:8080/webapi/shops/1
Accept: application/json

### get shops with figure
GET http://localhost:8080/webapi/figures/1/shops
Accept: application/json

### create new shop
POST http://localhost:8080/webapi/shops
Content-Type: application/json
Accept-Language: jp

{
  "name": "Sklep Janek2",
  "logo": "https://www.kinoteka.pl/img/logo.png"
}

###get all figures
GET http://localhost:8080/webapi/figures

###get figure by id
GET http://localhost:8080/webapi/figures/1

###get figures at stock in shop
GET http://localhost:8080/webapi/shops/1/figures

###create new figure
POST http://localhost:8080/webapi/figures
Content-Type: application/json

{
  "name": "IO",
  "material": "drewno!",
  "price": 2.50,
  "designerId": 4
}

### shutdown service
POST http://localhost:8080/actuator/shutdown